name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        version: 5.13.2
    - name: QMake and Make
      run: |
        qmake
        make -j2
    - name: Run Tests
      run: make check
      env:
        # Default platform plugins (like XCB) may
        # fail to initialize if they're run in a
        # GUI-less VM.
        QT_QPA_PLATFORM: minimal
